# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nfcore-kmermaid-0.1dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-data.table=1.11.4
  - r-gplots=3.0.1
  - bioconductor-edger=3.22.5
  - r-markdown=0.8
  - pytest
  - sphinx
  - matplotlib
  - alabaster
  - pip
  - fastp=0.20.0
  - fastqc
  - pathos=0.2.4
  - pysam=0.15.3
  - multiqc
  - python=3
  - pip:
    - git+https://github.com/czbiohub/kh-tools.git@olgabot/partition-coding-reads#egg=khtools
    - git+https://github.com/czbiohub/sourmash.git@master#egg=sourmash
    - git+https://github.com/czbiohub/bam2fasta.git@master#egg=bam2fasta
