# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-kmermaid-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-data.table=1.11.4
  - conda-forge::r-gplots=3.0.1
  - bioconda::bioconductor-edger=3.22.5
  - conda-forge::r-markdown=0.8
  - bioconda::khmer=2.1.2
  - pytest=5.3.4
  - sphinx=2.3.1
  - numpy=1.18.1
  - matplotlib=3.1.1
  - alabaster=0.7.12
  - conda-forge::gxx_linux-64
  - conda-forge::rust=1.40.0
  - ska=1.0
  - seqtk=1.3
  - pip=20.0.1
  - fastp=0.20.0
  - fastqc=0.11.8
  - pathos=0.2.4
  - pysam=0.15.3
  - multiqc=1.8
  - pip:
    - git+https://github.com/czbiohub/kh-tools.git@olgabot/partition-coding-reads#egg=khtools
    - git+https://github.com/czbiohub/sourmash.git@master#egg=sourmash
  # - conda-forge::gcc_linux-64
  # - gcc
